[backend]
bt_address = "08:B9:5F:D4:2D:58"
scanner_sleep_secs = 30

[webcam]
discovery_interface = "wlan0"
# in most cases, for discovery, credentials are not necessary
#discovery_username = "discovery_username"
#discovery_password = "discovery_password"
# either provide IP address or discovery interface
#ip_address = "192.168.100.161"
camera_username = "camera_username"
camera_password = "camera_password"
cloud_username = "admin"
cloud_password = "cloud_account_password"
snapshot_interval_secs = 40
debug = false
# HD (1080p), VGA (720p)
quality = "HD"

[frontend]
data_url = "http://localhost:8787/push"
image_url = "http://localhost:8787/image"
api_token = "api_token"
timeout_secs = 10
